name: Check Links

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.10"

            - name: Installing requirements
              run: python -m pip install --upgrade requests tqdm

            - name: Check Links
              run: python test_links.py

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: failed_links
                path: failed_links.txt